Added lock screen and css improvements
the-control-group/voyager pull request #1098
Opened 2017-04-08 22:39 UTC by davodavodavo3

Unit of measure 'px' is redundant 0px = 0pt = 0em = 0 :)
There is many CSS properties, which are being overwritten by default.I dont tuch them.

2017-04-08 22:43 UTC, davodavodavo3 commented
Old block structure:
![old](https://cloud.githubusercontent.com/assets/10462563/24832996/a70b65f4-1cc5-11e7-8e6c-16a948d5723e.jpg)

New block structure:
![accuracy](https://cloud.githubusercontent.com/assets/10462563/24832988/8e303686-1cc5-11e7-9348-182a744ef1ab.jpg)

Lock Screen page for admin users: 
![lock screen](https://cloud.githubusercontent.com/assets/10462563/24832999/d3c22858-1cc5-11e7-8bb4-b0c1cae03f7e.png)

2017-04-09 07:17 UTC, AdrianKuriata commented
Awesome!

2017-04-13 11:21 UTC, marktopper requested changes
Looks good @davodavodavo3. Great job.
One thing, please make a configuration for enabling/disabling the lock feature 👍

2017-04-13 15:00 UTC, fletch3555 commented on src/Http/Controllers/VoyagerController.php
> +        return redirect()->route('voyager.lock')->with($this->alertSuccess("Password is wrong!"));
`alertSuccess("Password is wrong!")` is counter-intuitive.. I'm sure you just used what was already there, but can this be changed somehow?  Should it be? @marktopper?

2017-04-13 20:59 UTC, davodavodavo3 commented
@marktopper Why add to the configuration, a functional that does not interfere with the user, it does not automatically turn on, only by clicking on it.

2017-04-13 21:03 UTC, davodavodavo3 commented
I can do changes in lockScreen method , if config lockscreen is true, or if in config->dashboard->navbar_items has item LockScreen

2017-04-18 18:01 UTC, akazorg commented
A configuration option would be great, maybe using an option type of time, where we define how many seconds before lock screen would turn active, while for disabling this feature we would set it to 0.

2017-05-26 10:46 UTC, DODMax commented
Up! Can we get this awesome feature?

I kind of agree that we don't need a setting, if user really don't want the *lock* link to show they can comment it in the `voyager.php` config file.

```php
    'dashboard' => [
        // Add custom list items to navbar's dropdown
        'navbar_items' => [
            /* ... */

            //'Lock' => [
            //    'route'      => 'voyager.lock',
            //    'icon_class' => 'voyager-lock',
            //],
            'Logout' => [
                'route'      => 'voyager.logout',
                'icon_class' => 'voyager-power',
            ],
        ],
```

2017-05-29 03:49 UTC, akazorg commented
Maybe this is a silly question, but why do we need a Lock screen, when we have a logout?

I like the idea of the auto lock - or should we call it auto-logout?

I know this somehow unrelated, but the user navbar dropdown should be handled by the Voyager Menu, or we loose the multilingual system for that nav. Besides, anyone can change the menu without the need of change the config file.

Ideas? Feedback?

2017-05-29 05:27 UTC, AdrianKuriata commented
@akazorg i think lockscreen is good when you need to go shop for 10minutes and you dont want logout from your account, but in house is someone who can do something bad on your account, this is enhacment, you know, this protect your account when you are away from keyboard.

2017-05-30 04:10 UTC, fletch3555 commented
I also don't understand the need for this.  Websites are intended to be stateless, with no single request being wholly dependent on another.  They should not be concerned about account security in this manner (and should instead just use session timeouts to force user logout for security).  A "lock screen" is more of an "OS" function, not one for a website.

This is equivalent to logout functionality (already exists) with the functionality to return to the last page you were on (arguably not needed if an app is designed well enough).

Consider this a down-vote from me.

2017-05-30 13:13 UTC, AdrianKuriata commented
I think you can lock it because davodavo wont change anything in this PR, he wanted help with improvement Voyager but time which is waste to update PR's is horrible, same for me so i dont help too.

2017-06-30 16:54 UTC, closed without merging