Update Russian translation
the-control-group/voyager pull request #1654
Opened 2017-09-03 15:11 UTC by Kleindberg

Add missing strings from English translation and correct some strings.

P.S. Why translation on site not update after voyager.php editing? Showing old texts.
P.P.S. Too many strings still untranslatable (not represent in voyager.php file).

2017-09-05 19:04 UTC, dmekhov requested changes

2017-09-05 19:04 UTC, dmekhov commented on publishable/lang/ru/voyager.php
> +        'auto_increment'         => 'Счётчик',
Don't translate this field: 'auto_increment' => 'Счётчик', 
Auto Increment is an established term

2017-09-05 19:04 UTC, dmekhov commented on publishable/lang/ru/voyager.php
> +        'unsigned'               => 'Не задано',
This is wrong translate: 'unsigned' => 'Не задано',
we can use 'unsigned' as established term or 'Без знаковое'

2017-09-05 19:04 UTC, dmekhov commented on publishable/lang/ru/voyager.php
> +        'help_key'             => 'Ключ параметра (например, admin_title)',
If you use "Мой параметр" as example of `help_name` - you must use "my_param" instead "admin_title" in `help_option` translation

2017-09-06 07:38 UTC, Kleindberg commented on publishable/lang/ru/voyager.php
> +        'auto_increment'         => 'Счётчик',
If this sring is not translatable, it would be better to remove it from translations.

2017-09-06 07:39 UTC, Kleindberg commented on publishable/lang/ru/voyager.php
> +        'unsigned'               => 'Не задано',
I don't know, that 'unsigned' in this translation is a modificator's name. It would be better to remove it from all translations.

2017-09-06 07:43 UTC, marktopper commented
To see the translations edit the configuration `locale` in `config/app.php`.

2017-09-06 07:53 UTC, Kleindberg commented
I solve a problem with outdated translations: just copied it from vendor folder to the public. I can't understand why we need a translations table in database if we use the files?

2017-09-06 08:04 UTC, marktopper commented
The translations table is for translating BREAD. Since BREAD is dynamicly inserted, the translations for that needs to be dynamic as well.

2017-09-06 08:22 UTC, merged