Bread remove error.
the-control-group/voyager pull request #1992
Opened 2017-10-12 18:09 UTC by kvlknctk

check row emtpy. it is searching json data in row.

2017-10-13 18:34 UTC, fletch3555 commented on src/Http/Controllers/VoyagerBreadController.php
> +            if ($row->field == "") {
I THINK you might have the logic backwards here...

2017-10-24 01:25 UTC, fletch3555 requested changes
Please change the `==` to `!=` per my other comment

2017-12-12 16:37 UTC, fletch3555 commented
@kvlknctk, you have merge conflicts and an outstanding change request.  Once these are resolved, we'll review and merge it.

2018-01-13 05:59 UTC, handiwijoyo commented
@kvlknctk Will you update this?

2018-03-20 01:18 UTC, fletch3555 commented
No response

2018-03-20 01:18 UTC, closed without merging