Fix for issue #2225
the-control-group/voyager pull request #2233
Opened 2017-11-15 15:49 UTC by dfk7677

Added a check for file _users/default.png_ (default avatar image) when deleting image files, as this file is not supposed to be deleted.

This is a fix for [#2225](https://github.com/the-control-group/voyager/issues/2225).

2017-11-20 16:27 UTC, fletch3555 commented
Please use feature branches when committing changes to open a PR.  You've now introduced additional changes into this PR (bc2b179).  Please revert these changes as they're unrelated and I can't accept the PR with them

2017-11-21 09:47 UTC, dfk7677 commented
I am sorry about this. Changes are reverted now.

2017-11-21 14:52 UTC, fletch3555 commented
Very good, thank you.

2017-11-22 17:09 UTC, emptynick commented
I think the filename should not be hardcoded, as it is a config var.
Just use:
`if ($data->{$row->field} != config('voyager.user.default_avatar')) {`

2017-11-22 18:29 UTC, fletch3555 requested changes

2017-11-22 18:29 UTC, fletch3555 commented on src/Http/Controllers/VoyagerBreadController.php
> +            if ($data->{$row->field} != 'users/default.png') {
As @emptynick suggested, `'users/default.png'` should not be hardcoded, and should be replaced with the config var.

2017-11-22 21:38 UTC, dfk7677 commented
Thanks @emptynick . Change done @fletch3555 .

2017-11-23 22:37 UTC, fletch3555 approved these changes

2017-11-23 22:37 UTC, fletch3555 commented
Perfect, thanks! @emptynick, have you given this a look from a QA perspective?  If all good, I can merge it

2017-12-05 21:22 UTC, emptynick commented
Yes I did, its working fine.
Just trying to think about any cases where this would get a prolem - but I cant think of any.

2017-12-05 21:43 UTC, fletch3555 commented
Nor can I, thanks!

2017-12-05 21:44 UTC, merged