Refactoring database tool index and saving some queries
the-control-group/voyager pull request #584
Opened 2017-01-16 14:35 UTC by Frondor

There was some evil `php` logic in the view, also a query inside a loop. Moved everything to the controller and cleaned the view.

2017-01-16 15:19 UTC, abdgad commented
I think it won't hurt if we change DBSchema::tables() to return an array of just table names, because it's only used in one place, in database index view.
```php
$tables = DB::select($query);

return array_map(function($table) {
    return current($table);
}, $tables);
```

2017-01-16 15:23 UTC, abdgad requested changes

2017-01-17 10:56 UTC, abdgad commented
there is a small bug: hidden tables are not handled properly.
`in_array($table, config('voyager.database.tables.hidden', []));`

2017-01-17 12:32 UTC, Frondor commented
Thanks for pointing that out, just fixed it.
The test for that route seems to be failing when accessing to `/admin/database` route, although in production I have no problems at all.

2017-01-17 15:58 UTC, merged