add cagetory id to post  datarow
the-control-group/voyager pull request #875
Opened 2017-03-06 13:08 UTC by aronpc

Fix category id in DataRowTableSeeder

2017-03-06 16:07 UTC, Dimsanchuk commented
Why type is "text"? If you are fixing this issue ([#835](https://github.com/the-control-group/voyager/issues/835)), I think type should be "select_dropdown".

2017-03-08 16:24 UTC, marktopper requested changes

2017-03-08 16:24 UTC, marktopper commented on publishable/database/seeds/DataRowsTableSeeder.php
> +                'type'         => 'text',
Please use the `select_dropdown` type, and add the `relationship` JSON option.

2017-03-11 19:03 UTC, fletch3555 reviewed
@marktopper, aren't we trying to phase-out the Pages/Posts/Categories stuff...? If so, I don't want these changes in there

Also, @aronpc, these aren't related to the original PR.  Please use separate git branches so you don't accidentally mess up an existing PR while working on something else.

2017-03-12 05:26 UTC, aronpc commented
> Also, @aronpc, these aren't related to the original PR. Please use separate git branches so you don't accidentally mess up an existing PR while working on something else.

Thanks

2017-03-12 05:26 UTC, closed without merging