active link menu
the-control-group/voyager pull request #907
Opened 2017-03-12 17:24 UTC by turtuga

Fix this 
![1](http://i.imgur.com/DRaJ2Bh.png)
to
![2](http://i.imgur.com/JmR96xd.png)

2017-03-12 20:56 UTC, marktopper requested changes

2017-03-12 20:56 UTC, marktopper commented on resources/views/menu/admin_menu.blade.php
> +        //$listItemClass = implode(" ", $listItemClass);
We should not leave commented out code like this

2017-03-12 20:59 UTC, turtuga commented on resources/views/menu/admin_menu.blade.php
> +        //$listItemClass = implode(" ", $listItemClass);
sorry changed :)

2017-03-12 20:59 UTC, marktopper approved these changes

2017-03-12 20:59 UTC, marktopper commented
Thanks, will test this out.

2017-03-13 16:42 UTC, marktopper commented
Everything works great, really great job 🎉

2017-03-13 16:42 UTC, merged

2017-03-13 22:22 UTC, akazorg commented
Great job! This was really missing