Added support for theming through introducing a function that checks …
the-control-group/voyager pull request #993
Opened 2017-03-22 14:27 UTC by Rndwiga

1. Added support for theming through introducing a function that checks whether theme support has been switched on, if so, it loads the theme if not it load default views
2. Theme support provided by caffeinated\themes

2017-03-24 09:35 UTC, marktopper requested changes
Just a minor change to limit the requirements.

According to this, I have a concern, do we limit the user to use the `caffeinated/themes` library for the admin panel only, or will they be able to run it for both Voyager and their own custom front-end?

2017-03-24 09:35 UTC, marktopper commented on composer.json
> +        "caffeinated/themes": "^3.0",
We can remove this from requirements and put it as a suggestion, and just note users that they need this when enabling the `use_theme` setting.

2017-04-17 16:56 UTC, fletch3555 commented
@Rndwiga, please respond to @marktopper's review comments

2017-06-21 13:09 UTC, closed without merging

2019-09-29 16:49 UTC, karneaud commented
Is this still applicable?

2019-09-29 16:55 UTC, fletch3555 commented
This has been closed for over 2 years now. Signficant changes have occurred since then.  You're much better off explaining your use-case and asking for help in our slack group instead